# Site settings
title: 木头同学
SEOTitle: 陈扬齐的博客 | 木头同学
header-img: img/post-bg-desk.jpg
email: 18569640023@163.com
description: "一个热爱code的优秀青年,哈哈!"
keyword: "陈扬齐, Blog, 陈扬齐的博客, chenyangqi, cyq, android, shundai, zhongyue,木头同学,木头童鞋"
url: "http://daleige.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/daleige/daleige.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "趁年轻,把生活终过成自己想要的样子"
sidebar-avatar: img/myhead.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     5138553269
zhihu_username:     mu-tou-tong-xue-35
github_username:    daleige
jianshu_username:   45ef413769c2
#twitter_username:   45ef413769c2




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus settings（https://disqus.com/）
disqus_username: chenyangqi

# 多说 将于2017年6月1日正式关停服务，建议使用 Disqus（http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241）
# Duoshuo settings
# duoshuo_username: qiubaiying
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
   {
        title: "简书·BY",
        href: "http://www.jianshu.com/u/45ef413769c2"
    },{
        title: "Androd",
        href: "https://developer.android.com/index.html"
    },{
        title: "GitHub",
        href: "https://github.com/daleige"
    }
]
